GLOBAL:
  IM_SIZE: 1024
  BATCH_SIZE: 2
  NUM_CLASSES: 3

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (1000, 2000)
  MAX_ITER: 4000
  GAMMA: 0.1
  # model_zoo, local, or detectron
  WEIGHTS: 'detectron2://ImageNetPretrained/MSRA/R-101.pkl'
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: 'WarmupMultiStepLR'
  WARMUP_FACTOR: 1.0 / 3
  WARMUP_ITERS: 500
  # batchsize * ITERS_PER_BATCH = total number of images
  ITERS_PER_BATCH: 100

TEST:
  IMS_PER_BATCH: 1
  CONF_THRESH: 0.7
  NMS_THRESH: 0.5

# ------------------------
# Model config
# ------------------------
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 101
    NUM_GROUPS: 1
    WIDTH_PER_GROUP: 64
    STRIDE_IN_1X1: False
    NORM: "GN"
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  ROI_HEADS:
    NAME: "StandardROIHeads"
    NUM_CLASSES: 3
    BOX_HEAD:
      NAME: "FastRCNNConvFCHead"
      NUM_CONV: 4
      NUM_FC: 2
      POOLER_TYPE: "ROIAlignV2"
      POOLER_RESOLUTION: 7
      POOLER_SAMPLING_RATIO: 2
      FC_DIM: 1024
    MASK_HEAD:
      NAME: "MaskRCNNConvUpsampleHead"
      NUM_CONV: 4
      CONV_DIMS: [256, 256, 256, 256]
      COMMON_STRIDE: 4
      NORM: "GN"
      UP_SCALE: 2